# Generated by Django 4.2.3 on 2023-07-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='bank_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='budget_id',
        ),
    ]
