# Generated by Django 4.2.3 on 2023-07-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loans',
            field=models.ManyToManyField(blank=True, to='finance.loan'),
        ),
        migrations.DeleteModel(
            name='MandatoryPayments',
        ),
    ]
