# Generated by Django 4.2.3 on 2023-08-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='limit_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.limitperiod'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='budgets',
            field=models.ManyToManyField(blank=True, to='finance.budget'),
        ),
        migrations.AddField(
            model_name='account',
            name='loans',
            field=models.ManyToManyField(blank=True, to='finance.loan'),
        ),
        migrations.AddField(
            model_name='account',
            name='main_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
