# Generated by Django 4.2.3 on 2023-07-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_loans_delete_mandatorypayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
