# Generated by Django 4.2.3 on 2023-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transactioncategory_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='budgets',
            field=models.ManyToManyField(blank=True, to='finance.budget'),
        ),
    ]
