# Generated by Django 4.2.3 on 2023-07-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
