# Generated by Django 4.2.3 on 2023-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_mandatorypayments_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatorypayments',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mandatorypayments',
            name='start_date',
            field=models.DateField(),
        ),
    ]
