# Generated by Django 4.2.3 on 2023-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='daily_limit_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
