# Generated by Django 4.2.3 on 2023-07-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_loan_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.transactioncategory'),
        ),
    ]
