# Generated by Django 4.2.3 on 2023-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_budget_daily_limit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
