# Generated by Django 4.2.3 on 2023-07-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_loan_loan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
