# Generated by Django 4.2.3 on 2023-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transactioncategory_is_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='value',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
