# Generated by Django 4.2.3 on 2023-07-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_description_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='value',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.description'),
        ),
    ]
