# Generated by Django 4.2.3 on 2023-07-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_description_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
            preserve_default=False,
        ),
    ]
