# Generated by Django 4.2.3 on 2023-07-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='main_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.currency'),
        ),
    ]
